### PR TITLE
Pull request with very unfinished miner.

### PR DESCRIPTION
**Pull request by NewbProgrammer101**
I added yet some more teachings to the priest.
I added support for wheat for the farmer.
I added a test miner. It still can't get to its designated area for mining. It can't wield a shovel or pickaxe when digging (I have no idea how that's done in Lua).

### CODE REVIEW

**Comment by NewbProgrammer101** [comment]
And I still haven't finished miner.png texture.

**Comment by NewbProgrammer101** [comment]
I really don't know how the files are conflicting.

**Comment by hkzorman** [comment]
Thanks! Much appreciated :+1: 

Two quick suggestions:
* I see the same changes that I have merged from your last pull request are being re-added again. Maybe you need to update your local project? To do this, just go to the root directory and do `git pull`
* For creating skins, you can use the skins available in `textures` folder and then modify it. You can actually use any online skin editor like this: http://www.minecraftskins.net/skineditor

Also, a quick observation: Occupations are currently still very WIP. I have modified (still not committed though) heavily the farmer's schedule entries. I will probably, however, use your code as a base and modify it as necessary.

Thanks again!

**Comment by NewbProgrammer101** [comment]
I resolved the conflicts and I gave you the miner.png file in the Minetest forums.
I will seek a way to fix these bugs described in the forums. :)

You can add this line: dofile(path .. "/data/occupations/default_miner.lua")
to init.lua

Because it's conflicting with your master branch.

**Comment by hkzorman** [comment]
This hasn't been overlooked, sorry, I have been busy and that's why I haven't commented.
I have finally finished most of the occupations code, and made changes to a lot of things.
I will probably get most of this code not by merging this PR but by actually merging your code manually in different commits as appropriate.

Also one thing: the `miner.png` is unfortunately not acceptable. It resembles too much Minecraft's Steve and it doesn't fit the style of the other NPC skins in here. Please rework your skin. I might also do it if you don't do it.

Overall, thanks! In the following days I will update here as I merge your changes!

**Comment by hkzorman** [comment]
Most of these commits has been merged.
Didn't merged:
 - The first three because they were before you rebased your version.
 - 3410b1ac331effb65fce5d89a278a860b6a11fb1 wasn't comitted as I want to fine tune the number of time it runs. The farmer will not be all day working on its fields.

Thanks for your contribution! Much appreciated :+1:

**Pull request closed without merging**
