### PR TITLE
Initiating documentation

### PR DESCRIPTION
**Pull request by BrunoMine**
This is an initial basic structuring of the documentation (based on the minetest documentation)

### CODE REVIEW

**Comment by BrunoMine** [comment]
I'm thinking of a more enjoyable way to view the API documentation, without having to keep two documentation (eg wiki)
Maybe a html page generator or maybe change the text documentation to md. I'm thinking about this in advance to avoid rework in the future.

**Comment by hkzorman** [comment]
This is a really fantastic job! These docs are great!
`.md` format is good enough for me.
I feel like the wiki might be unnecessary in the future, given these API docs you are working on...

**Comment by hkzorman** [comment]
@BrunoMine Do you want me to merge this as is and any other documentation changes to be added in the future, or would you to keep this open and add more docs here?

**Comment by BrunoMine** [comment]
I'm going to work on converting the .txt documentation to a .md. So this PR is not yet ready to be merged.

**Comment by BrunoMine** [comment]
Ok. It is ready.

**Comment by hkzorman** [comment]
Fantastic work. Thank you very much!

**Pull request merged**
