### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by BrunoMine**
This documentation updates and/or adds the following topics:

* Introduction
* Initialize NPC
* NPC Steps
* Programs
* Schedules
* Occupations
* Locations
* Dialogues
* Definition tables

### CODE REVIEW

**Comment by BrunoMine** [comment]
Okay, this is a good start to work. 
I want to take this opportunity to ask you to include the possibility of working strings in the flags.

**Comment by hkzorman** [comment]
Do you mean that you would like flags to have string values also?
Flags are deprecated, and will be replaces by `npc.data*` API (which is same as `npc.exec.var*` API but global, not per process) and that handles any value.

**Comment by BrunoMine** [comment]
Ok, you can merge now, and I'll work on updating this in the future.

**Comment by hkzorman** [comment]
Thanks, appreciated as always!

**Pull request merged**
