### PR TITLE
Make advanced_npc a pure API mod

### PR DESCRIPTION
**Pull request by hkzorman**
Fixes #53
 
This pull request will remove any data definition or NPC-specific code implementation and finally generalize `advanced_npc` to make it into a true API.

Task list:
  - [x] Remove all NPC textures
  - [x] Remove all registered data files
  - [x] Add a `npc.info*` API to register names and textures with metadata
  - [x] Generalize spawning functions to use any entity name
  - [x] Ensure `mg_villages` mod still working properly
  - [x] Clean out bugs and adapt functions that use texture and determine gender from them

More will be added as I understand what needs to be done in order to complete on this.

### CODE REVIEW

**Comment by hkzorman** [comment]
Hey @BrunoMine, could you please test this branch?
I'm afraid it might break something in your mod.

**Comment by hkzorman** [comment]
Actually, I downloaded your mod and tested. Fixed two issues, however, I'm not sure if everything is correct, I strongly recommend you to look at the NPC behavior and make sure they are still working properly (I saw one NPC switching back and forth between the kit culinario and crafting table, while I saw other that was very very still (never walked around). I'm not sure if that is the intended behavior or not, so please check.

And btw, congratulations on your mod so far! We seriously need mods that pay attention to details, and I can see yours is heading in that direction. I really like the houses, their layout, and the landscape around. Hopefully we can have smart NPCs living in those houses!

**Comment by BrunoMine** [comment]
The NPC behavior must be alternating between objects randomly. (dev brach)
I Will test this.

**Comment by BrunoMine** [comment]
The NPCs are using a wrong texture.

**Comment by BrunoMine** [comment]
Another problem detected. 
Apparently he is not running all the instructions in the queue.
See this code:
```lua
npc.programs.instr.register("sunos:rotate_to_pos", function(self, args)
	minetest.chat_send_all("sunos:rotate_to_pos")
	npc.programs.instr.execute(self, "advanced_npc:rotate", {
		start_pos = self.object:getpos(), 
		end_pos = args.pos,
	})
end)

npc.programs.instr.register("sunos:set_animation", function(self, args)
	minetest.chat_send_all("sunos:set_animation")
	self.object:set_properties({mesh = args.mesh})
	self.object:set_animation(
		{x = args.start_frame, y = args.end_frame},
        	args.frame_speed, 
        	0
        )
end)

-- Interagir aleatoriamente com a mobilia da casa
npc.programs.register("sunos:interagir_mobilia", function(self, args)
	
	-- Verificar distancia de casa
	if verif_dist_pos(self.object:getpos(), self.sunos_fundamento) > 16 then
		return
	end
	
	local places = npc.locations.get_by_type(self, "mobilia")
	
	p = places[math.random(1, #places)]
	
	npc.locations.add_shared(self, "sunos_alvo_mobilia", "sunos_alvo_mobilia", p.pos, p.access_node)
	
	npc.exec.proc.enqueue(self, "advanced_npc:interrupt", {
		new_program = "advanced_npc:walk_to_pos",
		new_args = {
			end_pos = {
				place_type="sunos_alvo_mobilia",
				use_access_node=true
			},
			walkable = sunos.estruturas.casa.walkable_nodes
		},
		interrupt_options = {}
	})
	
	-- Vira para "pos"
	npc.exec.proc.enqueue(self, "sunos:rotate_to_pos", {
		pos = p.pos,
	})
	
	-- Muda animação
	npc.exec.proc.enqueue(self, "sunos:set_animation", {
		mesh = "sunos_movimento_bancada.b3d",
		start_frame = 20,
		end_frame = 60,
		frame_speed = 25,
	})
	        
	-- Fica parado por um tempo
	npc.exec.proc.enqueue(self, "advanced_npc:wait", {
		time = 5,
	})
	
end)
```
I only get the `sunos:set_animation` message and I never get `sunos:rotate_to_pos`.

**Comment by hkzorman** [comment]
The texture issue is fixed, and opened a PR on your repo https://github.com/BrunoMine/sociedades/pull/8
I will check the queue issue next.

**Comment by hkzorman** [comment]
As you suggested, one of the instructions in queue was being dequeued before time.
This is now fixed in this branch.

Your mod seems to be working good. They are very hard workers!

**Comment by BrunoMine** [comment]
I'm still just testing this, I need to remember the blender. XD
I have oberserved two problems:
* The waiting time (`advanced_npc:wait`) is not being respected (you can put up to 50 seconds, he never expects it)
* The NPC is not walking (`advanced_npc:walk_to_pos`) to the exact location where it was sent (This is necessary for the effect in the animation).

**Comment by hkzorman** [comment]
This is on purpose, when I optimized the program to extra walks, it will just rotate toward the target node.
If you want I can add an option to avoid this and walk anyways... not sure how it will work though.

**Comment by BrunoMine** [comment]
This optimized program is very nice, is most common cases.
But in this specific case I need that the NPC walk for a exact pos. Pls add this opition.

**Comment by BrunoMine** [comment]
Thanks, I will continue my development, if I find any new problem I will inform.

**Comment by hkzorman** [comment]
Do not worry about docs... if you are referring to Info API, this one is not stable enough to start working on documentation.

**Comment by BrunoMine** [comment]
okay.
Apparently, the `walk_to_pos `problem still occurs when the node is diagonal to the NPC. I need the NPC to stay in the exact position.

**Comment by hkzorman** [comment]
I have been working on the walk_to_pos issue, still not having favorable results.
Regarding the schedules, I have performed a little change that changes the way they work. Before you could do `/time 6000` or any value and the schedule would change. I have done a change were the NPC won't process a schedule if its time is less than the previously processed time, e.g. if time is 9000, and you try `/time 6000` it won't work, it only goes forward. The only exception here is 23999 -> 0, which is allowed. Try changing time to 22950, let the log print `Time 23` and then set time to 23950. I think it should work.

**Comment by hkzorman** [comment]
Added a small change... please tell me if it improves, I'm currently unable to test properly.
Also, remember that in your `walk_to_pos` have the argument `optimize_one_node_distance` set to `false`.

**Comment by hkzorman** [comment]
Thank you, I will be taking a look at them. I currently have less time to work on the mod but will be addressing them soon.

**Comment by BrunoMine** [comment]
I'm developing all my mod based on that branch. As soon as I finish the next version (of my mod), I believe it will be stable enough to be released (this mod).

**Comment by hkzorman** [comment]
I'm also developing my mg_villages_npc mod with this branch, and there are few things that I change as I use it from an outside perspective. Please let me know when you are done with your mod.

**Comment by BrunoMine** [comment]
I think I'm ready to release the next version of my mod.
I will leave some things for the future releases (like dialogues), because I intend to wait until the basic problems and needs are completely solved.

**Comment by BrunoMine** [comment]
What should be the next step in your opnion? Launch the next version of the two projects or just mine project (in this case I will need to inform a dependency for the specific branch in your repository)? I believe that many other problems may appear after my release.

**Comment by BrunoMine** [comment]
After we solve all that. I'm going to propose the improvements that I'm already using in my project in a modular way (I'm trying to keep the code working in parallel to realize PR in the future).

**Comment by hkzorman** [comment]
@BrunoMine Done. Test the most recent push.

Regarding the release, thanks for raising that question. I believe we should both release new versions. While I'm aware that for this branch there could be more bugs, I believe it is stable enough for now. Tell me when you are fully done and I will try also to merge my branch with `master`.

**Comment by BrunoMine** [comment]
```txt
2018-06-22 20:55:53: WARNING[Server]: Undeclared global variable "occupation_name" accessed at ...Mods/minetest 0-5-0/bin/../mods/advanced_npc/npc.lua:582
2018-06-22 20:55:53: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'sunos' in callback luaentity_Activate(): ...Mods/minetest 0-5-0/bin/../mods/advanced_npc/npc.lua:131: bad argument #1 to 'unpack' (table expected, got nil)
2018-06-22 20:55:53: ERROR[Main]: stack traceback:
2018-06-22 20:55:53: ERROR[Main]: 	[C]: in function 'unpack'
2018-06-22 20:55:53: ERROR[Main]: 	...Mods/minetest 0-5-0/bin/../mods/advanced_npc/npc.lua:131: in function 'get_random_name'
2018-06-22 20:55:53: ERROR[Main]: 	...Mods/minetest 0-5-0/bin/../mods/advanced_npc/npc.lua:602: in function 'initialize'
2018-06-22 20:55:53: ERROR[Main]: 	...etest 0-5-0/bin/../mods/sociedades/sunos/npc/npc.lua:308: in function 'on_spawn'
2018-06-22 20:55:53: ERROR[Main]: 	...de Mods/minetest 0-5-0/bin/../mods/mobs_redo/api.lua:2504: in function <...de Mods/minetest 0-5-0/bin/../mods/mobs_redo/api.lua:2394>
2018-06-22 20:55:53: ERROR[Main]: 	(tail call): ?
2018-06-22 20:55:53: ERROR[Main]: 	[C]: in function 'add_entity'
2018-06-22 20:55:53: ERROR[Main]: 	...etest 0-5-0/bin/../mods/sociedades/sunos/npc/npc.lua:109: in function 'spawn'
2018-06-22 20:55:53: ERROR[Main]: 	...bin/../mods/sociedades/sunos/estruturas/casa/bau.lua:76: in function 'func_spawn'
2018-06-22 20:55:53: ERROR[Main]: 	...t 0-5-0/bin/../mods/sociedades/sunos/npc/spawner.lua:160: in function <...t 0-5-0/bin/../mods/sociedades/sunos/npc/spawner.lua:106>
```

**Comment by hkzorman** [comment]
Please check latest push, fad6531

By the way, I have forgotten to mention. I have added the ability to specify which search tags you want for choosing a NPC name when initializing it.

First you need to register a name:
```Lua
npc.info.register_name("Name1", {"sociedades", "male"})
npc.info.register_name("Name2", {"sociedades", "unisex"})
npc.info.register_name("Name3", {"advanced_npc", "unisex"})
```

Then, you can pass tags to `npc.initialize()` in the `npc_info` argument:
```Lua
npc.initialize(self, self.object:getpos(), true, nil, {name={tags={"sociedades"}}})
```

In the above example, only names with "sociedades" tag will be selected.

**Comment by BrunoMine** [comment]
ok, now this run without craches, but the tags not work.
```lua
-- Nomes de NPCs (derivados do esperanto)
sunos.var.npc_names = {
	male = {
		"Lumo", -- Luz
		"Racio", -- Razão
		"Honoro", -- Honra
		"Akurata", -- Pontual
		"Bonfama", -- de boa fama
		"Bonulo", -- Bom
		"Kora", -- Cordial
		"Negro", -- Negro
		"Obei", -- Obedecer
		"Obstini", -- Teimar
		"Poeto", -- Poeta
		"Trunko", -- Tronco
		"Flavo", -- Amarelo
	},
	female = {
		"Flava", -- Amarela
		"Hela", -- Luminosa
		"Brava", -- valente
		"Afable", -- Amavel
		"Bela", -- Bela
		"Danka", -- Grato
		"Eleganta", -- Elegante
		"Epopea", -- Épico
		"Negra", -- Negra
		"Nigra", -- Negra
		"Obeema", -- Obediente
	},
}
for _, name in ipairs(sunos.var.npc_names.male) do
	npc.info.register_name(name, {"male", "sunos"})
end
for _, name in ipairs(sunos.var.npc_names.female) do
	npc.info.register_name(name, {"female", "sunos"})
end
```
```lua
if self.initialized == nil then
	npc.initialize(self, self.object:getpos(), true, nil, {name={tags={"sunos"}}})
	self.tamed = false
end
```
Results:
```txt
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with occupation values
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Initializing NPC at (9012,9.5,4780)
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: NPC Inventory: {
	"default:iron_lump 7",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	""
}
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with name "Anonymous", gender: male, is child: nil, texture: {
	"sunos_npc_male.png"
}
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Overriding NPC values using occupation '"sunos_npc_caseiro"' values
2018-06-22 22:46:35: [Server]: Result: "sunos_npc_male.png"
2018-06-22 22:46:35: [Server]: def.properties: nil
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with occupation values
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Initializing NPC at (9013,9.5,4781)
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with name "Anonymous", gender: female, is child: nil, texture: {
	"sunos_npc_female.png"
}
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Overriding NPC values using occupation '"sunos_npc_caseiro"' values
2018-06-22 22:46:35: [Server]: Result: "sunos_npc_female.png"
2018-06-22 22:46:35: [Server]: def.properties: nil
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with occupation values
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Initializing NPC at (9022,9.5,4779)
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with name "Anonymous", gender: female, is child: nil, texture: {
	"sunos_npc_male.png"
}
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Overriding NPC values using occupation '"sunos_npc_caseiro"' values
2018-06-22 22:46:35: [Server]: Result: "sunos_npc_female.png"
2018-06-22 22:46:35: [Server]: def.properties: nil
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with occupation values
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Initializing NPC at (9033,9.5,4783)
2018-06-22 22:46:35: [Server]: [advanced_npc] INFO: Successfully initialized NPC with name "Anonymous", gender: female, is child: nil, texture: {
	"sunos_npc_female.png"
}
```

**Comment by hkzorman** [comment]
Please try with latest push, I have tried in my local and the names you provided seem to be assigned correctly. However, the textures are not. I saw a male getting the female texture, not sure why.

Will try to check why.

**Comment by BrunoMine** [comment]
Okay, this is okay for merge, my project woks fine.

**Comment by hkzorman** [comment]
Awesome, I guess you will test before doing any formal release, right?

**Comment by BrunoMine** [comment]
I have already done several tests so far, I believe it is 90% functional. After the launch, new problems may appear. But we need to launch to test.
Launch your version first, so users can download the new version of advanced_api.

**Comment by hkzorman** [comment]
Merged at last.
Release is here: https://github.com/hkzorman/advanced_npc/releases/tag/1.0.0-alpha-2

**Pull request merged**
